import React from "react";
import * as Icon from "react-feather";
const navigationConfig = [
  {
    id: "groupheader5",
    type: "groupHeader",
    groupTitle: "PHÒNG CÔNG TÁC ",
    permissions: ["admin"],
  },
  {
    id: "totalSupport",
    title: "Tổng hợp",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/",
  },
  {
    id: "searchStudentAssistant",
    title: "Tra cứu",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/assistant/search",
  },
  {
    id: "list ",
    title: "Danh sách ",
    type: "collapse",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    children: [
      {
        id: "listStudentAssistant",
        title: "Ds.Sinh viên",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/assistant/list/student",
      },
      {
        id: "listTeacherAssistant",
        title: "Ds.Giáo viên",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/assistant/list/teacher",
      },
      {
        id: "listClassAssistant",
        title: "Ds.Lớp",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/assistant/list/class",
      },
      {
        id: "listSubjectAssistant",
        title: "Ds.Môn",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/assistant/list/subject",
      },
      {
        id: "listStage",
        title: "Ds.Khóa học",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/assistant/list/stage",
      },
      {
        id: "listSeason",
        title: "Ds.Kì học",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/assistant/list/season",
      },
    ],
  },
  {
    id: "groupheader1",
    type: "groupHeader",
    groupTitle: "Phòng đào tạo",
    permissions: ["admin"],
  },
  {
    id: "totalDepartment",
    title: "Tổng hợp",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/education/totalDepartment",
  },
  {
    id: "generalDepartment",
    title: "Phân lớp",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/department",
  },
  {
    id: "listDepartment",
    title: "Danh sách",
    type: "collapse",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    children: [
      {
        id: "listStudentDepartment",
        title: "Ds.Sinh viên",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/education/student",
      },
      {
        id: "listTeacherDepartment",
        title: "Ds.Giảng viên",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/education/teacher",
      },
      {
        id: "listClassDepartment",
        title: "Ds.Lớp",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/education/class",
      },
      {
        id: "listSubjectDepartment",
        title: "Ds.Môn ",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/education/subject",
      },
      {
        id: "listStage",
        title: "Ds.Khóa học",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/education/stage",
      },
      {
        id: "listSeason",
        title: "Ds.Kì học",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/education/season",
      },
      {
        id: "listSpecialization",
        title: "Ds.Chuyên ngành",
        type: "item",
        icon: <Icon.FileText size={18} />,
        permissions: ["admin"],
        navLink: "/education/specialization",
      },
    ],
  },
  {
    id: "groupheader5",
    type: "groupHeader",
    groupTitle: "Giảng viên",
    permissions: ["admin"],
  },
  {
    id: "generalTeacher",
    title: "Lớp dạy",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/teacher/listClass",
  },
  {
    id: "attendance",
    title: "Điểm danh",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/teacher/attendance",
  },
  {
    id: "emailTeacher",
    title: "Hộp thư GV",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/teacher/email",
  },
  {
    id: "LiveSteamTeacher",
    title: "Học trực tuyến",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/teacher/liveStream",
  },
  {
    id: "groupheader5",
    type: "groupHeader",
    groupTitle: "Thông báo",
    permissions: ["admin"],
  },
  {
    id: "blog",
    title: "Thông báo",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/admin/blog",
  },
  //------------------
  // Student
  //-----------------

  {
    type: "groupHeader",
    groupTitle: "Sinh viên",
    permissions: ["admin", "student"],
  },
  {
    id: "generalStudent",
    title: "Thông báo chung",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "student"],
    navLink: "/student/news",
  },
  {
    id: "scoreStudent",
    title: "Điểm học",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "student"],
    navLink: "/student/score",
  },
  {
    id: "scheduleStudent",
    title: "Lịch học",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "student"],
    navLink: "/student/schedule",
  },
  {
    id: "attendanceCheckList",
    title: "Điểm danh",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "student"],
    navLink: "/student/attendance",
  },
  {
    id: "leaningStudent",
    title: "Học trực tuyến",
    type: "collapse",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "student"],
    children: [
      {
        id: "documentStudent",
        title: "Tài liệu và bài tập",
        type: "item",
        icon: <Icon.Download size={15} />,
        permissions: ["admin", "student"],
        navLink: "/student/document",
      },
      {
        id: "livesteamStudent",
        title: "Điểm danh",
        type: "item",
        icon: <Icon.Airplay size={15} />,
        permissions: ["admin", "student"],
        navLink: "/student/livestream",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Trò truyện",
    permissions: ["admin", "student", "teacher"],
  },
  {
    id: "Hội họp",
    title: "chat",
    type: "item",
    icon: <Icon.MessageCircle size={15} />,
    permissions: ["admin", "student", "Chat"],
    navLink: "/chat",
  },
  {
    type: "groupHeader",
    groupTitle: "admin",
    permissions: ["admin"],
  },
  {
    id: "accountTeacher",
    title: "Tài khoản giáo viên",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/admin/account/teacher",
  },
  {
    id: "accountDaotao",
    title: "Tài khoản đào tạo",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/admin/account/educate",
  },
  {
    id: "accountSupportStudent",
    title: "Tài khoản CTSV",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin"],
    navLink: "/admin/account/suport",
  },
];

export default navigationConfig;
