export const GET_SEMESTER = "GET_SEMESTER";
export const GET_SEMESTER_SUCCESS = "GET_SEMESTER_SUCCESS";
export const GET_SEMESTER_FAIL = "GET_SEMESTER_FAIL";

export const GET_SUBJECT_FROM_CLASS = "GET_SUBJECT_FROM_CLASS";
export const GET_SUBJECT_FROM_CLASS_SUCCESS = "GET_SUBJECT_FROM_CLASS_SUCCESS";
export const GET_SUBJECT_FROM_CLASS_FAIL = "GET_SUBJECT_FROM_CLASS_FAIL";

export const GET_BOTHSTUDY = "GET_BOTHSTUDY";
export const GET_BOTHSTUDY_SUCCESS = "GET_BOTHSTUDY_SUCCESS";
export const GET_BOTHSTUDY_FAIL = "GET_BOTHSTUDY_FAIL";

export const GET_SPECIALIZATION = "GET_SPECIALIZATION";
export const GET_SPECIALIZATION_SUCCESS = "GET_SPECIALIZATION_SUCCESS";
export const GET_SPECIALIZATION_FAIL = "GET_SPECIALIZATION_FAIL";
