export const GET_SEMESTER = "GET_SEMESTER";
export const GET_SEMESTER_SUCCESS = "GET_SEMESTER_SUCCESS";
export const GET_SEMESTER_FAIL = "GET_SEMESTER_FAIL";

export const GET_SUBJECT_FROM_CLASS = "GET_SUBJECT_FROM_CLASS";
export const GET_SUBJECT_UPDATE = "GET_SUBJECT_UPDATE";
export const GET_SUBJECT_FROM_CLASS_SUCCESS = "GET_SUBJECT_FROM_CLASS_SUCCESS";
export const GET_SUBJECT_FROM_CLASS_FAIL = "GET_SUBJECT_FROM_CLASS_FAIL";

export const GET_BOTHSTUDY = "GET_BOTHSTUDY";
export const GET_BOTHSTUDY_SUCCESS = "GET_BOTHSTUDY_SUCCESS";
export const GET_BOTHSTUDY_FAIL = "GET_BOTHSTUDY_FAIL";

export const GET_SPECIALIZATION = "GET_SPECIALIZATION";
export const GET_SPECIALIZATION_SUCCESS = "GET_SPECIALIZATION_SUCCESS";
export const GET_SPECIALIZATION_FAIL = "GET_SPECIALIZATION_FAIL";
export const UPDATE_DATA_SPECIALIZATION = "UPDATE_DATA_SPECIALIZATION";
export const SET_TASK_SPECIALIZATION = "SET_TASK_SPECIALIZATION";

export const ADD_SCHEDULES = "ADD_SCHEDULES";
export const UPDATE_SCHEDULES = "UPDATE_SCHEDULES";
export const DELETE_SCHEDULES = "DELETE_SCHEDULES";
