export const GET_DATA_SCHEDULE_STUDENT_ID = "GET_DATA_SCHEDULE_STUDENT_ID";
export const GET_DATA_SCHEDULE_STUDENT_ID_SUCCESS =
  "GET_DATA_SCHEDULE_STUDENT_ID_SUCCESS";
export const GET_DATA_SCHEDULE_STUDENT_ID_FAIL =
  "GET_DATA_SCHEDULE_STUDENT_ID_FAIL";
export const GET_DATA_SCHEDULE_STUDENT_ID_DETAIL =
  "GET_DATA_SCHEDULE_STUDENT_ID_DETAIL";
export const GET_DATA_SCHEDULE_STUDENT_ID_DETAIL_SUCCESS =
  "GET_DATA_SCHEDULE_STUDENT_ID_DETAIL_SUCCESS";
export const GET_DATA_SCHEDULE_STUDENT_ALL = "GET_DATA_SCHEDULE_STUDENT_ALL";
export const GET_DATA_SCHEDULE_STUDENT_ALL_SUCCESS =
  "GET_DATA_SCHEDULE_STUDENT_ALL_SUCCESS";
export const GET_DATA_PROFILE_STUDENT = "GET_DATA_PROFILE_STUDENT";
export const GET_DATA_PROFILE_sTUDENT_SUCCESS =
  "GET_DATA_PROFILE_sTUDENT_SUCCESS";
