export const GET_DATA_SCHEDULE_STUDENT_ID = "GET_DATA_SCHEDULE_STUDENT_ID";
export const GET_DATA_SCHEDULE_STUDENT_ID_SUCCESS =
  "GET_DATA_SCHEDULE_STUDENT_ID_SUCCESS";
export const GET_DATA_SCHEDULE_STUDENT_ID_FAIL =
  "GET_DATA_SCHEDULE_STUDENT_ID_FAIL";
