
export const JOIN_FRIEND = " JOIN_FRIEND";
export const JOIN_FRIEND_SUCCESS = "JOIN_FRIEND_SUCCESS";
export const GET_MESSAGE_ID_GROUP = "GET_MESSAGE_ID_GROUP";
export const GET_MESSAGE_ID_GROUP_SUCCESS = "GET_MESSAGE_ID_GROUP_SUCCESS";
export const SEND_CHAT = "SEND_CHAT";
export const SEND_CHAT_SUCCESS = "SEND_CHAT_SUCCESS";
export const RECEIEVE_CHAT_SOCKET = "RECEIEVE_CHAT_SOCKET";
export const GET_ALL_DATA_GROUP = "GET_ALL_DATA_GROUP";
export const GET_ALL_DATA_GROUP_SUCCESS = "GET_ALL_DATA_GROUP_SUCCESS";
export const SEARCH_USER_CHAT = "SEARCH_USER_CHAT";
export const SEARCH_CHAT_USER_SUCCESS = "SEARCH_CHAT_USER_SUCCESS";
export const SEARCH_CHAT_USER_FAIL = "SEARCH_CHAT_USER_FAIL";

export const ADD_CHAT_GROUP = "ADD_CHAT_GROUP"

export const STORE_SAVE_GROUP_CHAT = "STORE_SAVE_GROUP_CHAT"

export const SET_CONTACT = "SET_CONTACT"