///assist student
export const GET_DATA_STUDENT_ASS = "GET_DATA_STUDENT_ASS";
export const GET_DATA_STUDENT_ASS_SUCCE = "GET_DATA_STUDENT_ASS_SUCCE";
export const GET_DATA_STUDENT_ASS_FAILD = "GET_DATA_STUDENT_ASS_FAILD";
