/**
 * assist student
 */
export const GET_DATA_STUDENT_ASS = "GET_DATA_STUDENT_ASS";
export const GET_DATA_STUDENT_ASS_SUCCE = "GET_DATA_STUDENT_ASS_SUCCE";
export const GET_DATA_STUDENT_ASS_FAILD = "GET_DATA_STUDENT_ASS_FAILD";
export const EXPORT_EXCEL_STUDENT = "EXPORT_EXCEL_STUDENT";
/**
 * assist teacher
 */
export const GET_DATA_TEACHER_ASS = "GET_DATA_TEACHER_ASS ";
export const GET_DATA_TEACHER_ASS_SUCCESS = "GET_DATA_TEACHER_ASS_SUCCESS";
export const GET_DATA_TEACHER_ASS_FAILD = "GET_DATA_TEACHER_ASS_FAILD";
export const EXPORT_EXCEL_TEACHER = "EXPORT_EXCEL_TEACHER";

/**
 * assist class
 */
export const GET_DATA_CLASS_ASS = "GET_DATA_CLASS_ASS ";
export const GET_DATA_CLASS_ASS_SUCCESS = "GET_DATA_CLASS_ASS_SUCCESS";
export const GET_DATA_CLASS_ASS_FAILD = "GET_DATA_CLASS_ASS_FAILD";
/**
 * assist subject
 */
export const GET_DATA_SUBJECT_ASS = "GET_DATA_SUBJECT_ASS ";
export const GET_DATA_SUBJECT_ASS_SUCCESS = "GET_DATA_SUBJECT_ASS_SUCCESS";
export const GET_DATA_SUBJECT_ASS_FAILD = "GET_DATA_SUBJECT_ASS_FAILD";
/**
 * assist state
 */
export const GET_DATA_STAGE = "GET_DATA_STAGE";
export const GET_DATA_STAGE_SUCCESS = "GET_DATA_STAGE_SUCCESS";
export const GET_DATA_STAGE_FAIL = "GET_DATA_STAGE_FAIL";
/**
 * assist season
 */
export const GET_DATA_SEASON = "GET_DATA_SEASON";
export const GET_DATA_SEASON_SUCCESS = "GET_DATA_SEASON_SUCCESS";
export const GET_DATA_SEASON_FAIL = "GET_DATA_SEASON_FAIL";
