export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const ADD_BLOG = "ADD_BLOG";

export const DELETE_BLOG = "DELETE_BLOG";

export const GET_ALL_NOTIFY = "GET_ALL_NOTIFY";
export const GET_ALL_NOTIFY_SUCCESS = "GET_ALL_NOTIFY_SUCCESS";
export const GET_ALL_NOTIFY_FAIL = "GET_ALL_NOTIFY_FAIL";

export const SET_TASK_EDIT_BLOG = "SET_TASK_EDIT_BLOG";
export const UPDATE_BLOG = "UPDATE_BLOG";

export const GET_NOTI_FEE_STUDENT = "GET_NOTI_FEE_STUDENT";
export const GET_NOTI_FEE_STUDENT_SUCCESS = "GET_NOTI_FEE_STUDENT_SUCCESS";

export const GET_NOTI_ACTIVITY_STUDENT = "GET_NOTI_ACTIVITY_STUDENT";
export const GET_NOTI_ACTIVITY_STUDENT_SUCCESS =
  "GET_NOTI_ACTIVITY_STUDENT_SUCCESS";

export const GET_NOTI_LEARNING_STUDENT = "GET_NOTI_LEARNING_STUDENT";
export const GET_NOTI_LEARNING_STUDENT_SUCCESS =
  "GET_NOTI_LEARNING_STUDENT_SUCCESS";

export const GET_NOTI_SOCKET_FEE = "GET_NOTI_SOCKET_FEE";

export const GET_NOTI_SOCKET_ACTIVITY = "GET_NOTI_SOCKET_ACTIVITY";
export const GET_NOTI_SOCKET_LEARNING = "GET_NOTI_SOCKET_LEARNING";
export const GET_ALL_NOTI_SOCKET = "GET_ALL_NOTI_SOCKET";

export const CHECK_USER_SEEN_NOTI = "CHECK_USER_SEEN_NOTI";
