export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const ADD_BLOG = "ADD_BLOG";

export const DELETE_BLOG = "DELETE_BLOG";

export const GET_ALL_NOTIFY = "GET_ALL_NOTIFY";
export const GET_ALL_NOTIFY_SUCCESS = "GET_ALL_NOTIFY_SUCCESS";
export const GET_ALL_NOTIFY_FAIL = "GET_ALL_NOTIFY_FAIL";

export const SET_TASK_EDIT_BLOG = "SET_TASK_EDIT_BLOG";
export const UPDATE_BLOG = "UPDATE_BLOG";
