export const IMPORT_EXCEL_STUDENT = "IMPORT_EXCEL_STUDENT";
export const IMPORT_EXCEL_sTUDENT_SUCCESS = "IMPORT_EXCEL_sTUDENT_SUCCESS";
export const IMPORT_EXCEL_sTUDENT_FAIL = "IMPORT_EXCEL_sTUDENT_FAIL";
