export const GET_SCHEDULES_TEACHER = "GET_SCHEDULES_TEACHER";
export const GET_SCHEDULES_TEACHER_SUCCESS = "GET_SCHEDULES_TEACHER_SUCCESS";
export const GET_SCHEDULES_TEACHER_FAIL = "GET_SCHEDULES_TEACHER_FAIL";

export const GET_SCHEDULE_ID = "GET_SCHEDULE_ID";
export const GET_SCHEDULE_ID_SUCCESS = "GET_SCHEDULE_ID_SUCCESS";
export const GET_SCHEDULE_ID_FAIL = "GET_SCHEDULE_ID_FAIL";

export const SCHEDULES = "SCHEDULES";

export const GET_PROFILE_TEACHER = "GET_PROFILE_TEACHER";
export const GET_PROFILE_TEACHER_SUCCESS = "GET_PROFILE_TEACHER_SUCCESS";
