export const GET_DATA_TRANSACTION = "GET_DATA_TRANSACTION";
export const GET_DATA_TRANSACTION_SUCCESS = "GET_DATA_TRANSACTION_SUCCESS";
export const GET_DATA_TRANSACTION_FAILD = "GET_DATA_TRANSACTION_FAILD";

export const TRANSACTION_SEARCH = "GET_DATA_TRANSACTION_SEARCH";
export const TRANSACTION_SEARCH_SUCCESS = "GET_DATA_TRANSACTION_SEARCH_SUCCESS";
export const TRANSACTION_SEARCH_FAILD = "GET_DATA_TRANSACTION_SEARCH_FAILD";

export const UPDATE_STATUS_TRANSACTION_APPROVED =
  "UPDATE_STATUS_TRANSACTION_APPROVED";
export const UPDATE_TRANSACTION_DONE = "UPDATE_TRANSACTION_DONE";
