export const GET_DATA_SHOP = "GET_DATA_SHOP";
export const ADD_DATA_SHOP = "ADD_DATA_SHOP";
export const DELETE_DATA_SHOP = "DELETE_DATA_SHOP";
export const UPDATE_DATA_SHOP = "UPDATE_DATA_SHOP";
export const GET_DATA_SHOP_CATEGORY = "GET_DATA_SHOP_CATEGORY";
