export const GET_DATA_TRANSACTION = "GET_DATA_TRANSACTION";
export const GET_DATA_TRANSACTION_SUCCESS = "GET_DATA_TRANSACTION_SUCCESS";
export const GET_DATA_TRANSACTION_FAILD = "GET_DATA_TRANSACTION_FAILD";

export const UPDATE_STATUS_TRANSACTION = "UPDATE_STATUS_TRANSACTION";
